spring:
  application:
    name: Index-Config-Server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://gitee.com/Maxwell-L/TrendConfig
          search-paths: repo
          skip-ssl-validation: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
